spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autobase
    username: postgres
    password: 8289/00/5654
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect